/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sabathquiz;

import bean.Question;
import bean.Answer;
import bean.Quizz;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JButton;


/**
 *
 * @author wesinalves
 */
public class QuestionDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuestionDialog
     */
    
    public JButton[] btArray;
    
    List<Answer> listAnswer;
           
    Clip applauseSound;
    
    Clip boomSound;
    
    Quizz qzz;
    
    public QuestionDialog(Quizz quizz, Question question, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JButton[] buttonArray = {jButton1, jButton2, jButton3, jButton4};
        btArray = buttonArray;
        listAnswer = new ArrayList<>();
        listAnswer = question.getAnswers();
        qzz = quizz;
        txtDescription.setText(question.getDescription());
        for(int i = 0; i < buttonArray.length; i++){
            btArray[i].setText((i+1) + ") " +listAnswer.get(i).getDescription());
        }
        
        this.setTitle(question.getNumber());
        
        openSounds();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescription = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        txtDescription.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescription.setText("jLabel2");
        getContentPane().add(txtDescription);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("jButton3");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setText("jButton4");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getAnswer();
        if(listAnswer.get(0).getValue() == true){
            // set parcial quizz result
            qzz.setResult(qzz.getResult() + 1);
            //play aplauses
            playApplause();
        }else{
            //play boom
            playBoom();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        getAnswer();
        if(listAnswer.get(1).getValue() == true){
            // set parcial quizz result
            qzz.setResult(qzz.getResult() + 1);
            //play aplauses
            playApplause();
            
        }else{
            //play boom
            playBoom();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        getAnswer();
        if(listAnswer.get(2).getValue() == true){
            // set parcial quizz result
            qzz.setResult(qzz.getResult() + 1);
            //play aplauses
            playApplause();
        }else{
            //play boom
            playBoom();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        getAnswer();
        if(listAnswer.get(3).getValue() == true){
            // set parcial quizz result
            qzz.setResult(qzz.getResult() + 1);
            //play aplauses
            playApplause();
        }else{
            //play boom
            playBoom();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

 
private void getAnswer(){
        
    if(listAnswer.get(0).getValue() == true){
            btArray[0].setBackground(Color.green);
            btArray[1].setBackground(Color.red);
            btArray[2].setBackground(Color.red);
            btArray[3].setBackground(Color.red);
    }else if(listAnswer.get(1).getValue() == true){
            btArray[0].setBackground(Color.red);
            btArray[1].setBackground(Color.green);
            btArray[2].setBackground(Color.red);
            btArray[3].setBackground(Color.red);
    }else if(listAnswer.get(2).getValue() == true){
            btArray[0].setBackground(Color.red);
            btArray[1].setBackground(Color.red);
            btArray[2].setBackground(Color.green);
            btArray[3].setBackground(Color.red);
    }else if(listAnswer.get(3).getValue() == true){
            btArray[0].setBackground(Color.red);
            btArray[1].setBackground(Color.red);
            btArray[2].setBackground(Color.red);
            btArray[3].setBackground(Color.green);
    }
    
    
}

private void openSounds(){
        try{
            AudioInputStream applauseStream = AudioSystem.getAudioInputStream(new File("src/audio/palmas.wav").getAbsoluteFile());
            AudioInputStream boomStream = AudioSystem.getAudioInputStream(new File("src/audio/carreta.wav").getAbsoluteFile());
            applauseSound = AudioSystem.getClip();
            applauseSound.open(applauseStream);
            
            boomSound = AudioSystem.getClip();
            boomSound.open(boomStream);
                                    
        }
        catch(FileNotFoundException exc){
            exc.printStackTrace();
            System.out.println("Failed to play the file.");
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(QuestionDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
}


private void playApplause() {
    try{
            applauseSound.start();
        }
     catch(Exception exc){
            exc.printStackTrace();
            System.out.println("Failed to play the file.");
        }
    }

private void playBoom(){
    try{
            
            boomSound.start();
        }
    catch(Exception exc){
            exc.printStackTrace();
            System.out.println("Failed to play the file.");
    }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtDescription;
    // End of variables declaration//GEN-END:variables

    
}
